### ISSUE TITLE
Add a bust/half body?

### ISSUE THREAD

**Issue by bribes** [NickAcPT/nmsr-rs#2]
Title ^

**Comment by NickAcPT** [comment]
> Title ^

@bribes Thanks a lot for the suggestion!
Currently nmsr is pending a rewrite since it's very limited on what it can do.

In the meanwhile, I suggest making use of [Visage](https://visage.surgeplay.com/index.html) since they have exactly what you're looking for, along with some extra customizability of the camera positioning if needed.

I'll leave this issue open for when that rewrite happens.

**Comment by NickAcPT** [comment]
_Oh god, how is it almost 2024 already?!_

This got implemented in the `nmsr-aas/next` branch and it finally got merged to main.
Feature hasn't been rolled out in the public hosted version as that is pending a homepage rewrite though. I'll update this message when I roll out the extra render modes.
