### ISSUE TITLE
Custom skins servers

### ISSUE THREAD

**Issue by IkyMax** [NickAcPT/nmsr-rs#7]
Hey! more than an issue this is only a question lol

I have a self hosted Yggrasil API but it doesnt include a skin renderer on its own... So, i was wondering, its possible to use this project to use my own session server and textures? i tried with Crafatar but it doesnt work, maybe bcs the uuids on my session server are trimmed? idk

**Comment by NickAcPT** [comment]
Hey there! Yes, it is possible to use a custom skin server. For that, you'll need to change two settings in the config file.

If you aren't using a config file, then make a copy of the example file and change [these](https://github.com/NickAcPT/nmsr-rs/blob/main/example.config.toml#L50-L59) lines to point to your session and textures server.

About the shorter UUIDs, can you provide an example of one? I have set a minimum length for them in the code but if needed I can try to relax that rule.

**Comment by ErinMax** [comment]
Oh, thx! idk if this is an issue but my textures server have a folder for skins and capes, its specified on the session server but idk if it would have any effect here

And yes!

Normal UUID: 343036ff-f42f-392f-b7fc-145be1e9082a
Trimmed UUID: 343036fff42f392fb7fc145be1e9082a

**Comment by NickAcPT** [comment]
> Oh, thx! idk if this is an issue but my textures server have a folder for skins and capes, its specified on the session server but idk if it would have any effect here

Umm, that depends on the URL. Right now the code does the following URL format: `{textures_server}/texture/{texture_id}` where `{textures_server}` is the URL in the config.

Is that format okay or do you need a more customizable setting? I don't mind changing it.

> And yes!
> 
> Normal UUID: 343036ff-f42f-392f-b7fc-145be1e9082a
> Trimmed UUID: 343036fff42f392fb7fc145be1e9082a

Trimmed UUIDs are supported yes. However, I do notice that you're using version 3 UUIDs (so offline mode) which the code will yell at you since I check for that.

Tomorrow I'll add a setting to make it so it doesn't do online mode checks.

**Comment by ErinMax** [comment]
> Umm, that depends on the URL. Right now the code does the following URL format: `{textures_server}/texture/{texture_id}` where `{textures_server}` is the URL in the config.

Oh, then there is a problem because my url is `{textures_server}/texture/(skin or cape)/{texture_id}`

> Trimmed UUIDs are supported yes. However, I do notice that you're using version 3 UUIDs (so offline mode) which the code will yell at you since I check for that.
> 
> Tomorrow I'll add a setting to make it so it doesn't do online mode checks.

Oh yeah, im using v3 UUID's bcs my server was offline mode on mojang servers so i switched to this auth server and asked my users to create a account with their offline UUID's to make the auth servers migration easier, thx in advice!

**Comment by NickAcPT** [comment]
Added the following settings in the mojank section:
| Setting | Description | Default |
| --- | --- | --- |
| `allow_offline_mode_uuids` | Whether to allow offline mode UUIDs. | `false` |
| `use_dashless_uuids` | Whether to use dashless UUIDs when requesting the Mojang API. | `false` |
| `textures_server_skin_url_template` | The template to use for the player skin textures URL. | `{textures_server}/texture/{texture_id}` |
| `textures_server_cape_url_template` | The template to use for the player cape textures URL. | `{textures_server}/texture/{texture_id}` |

For more information on how to configure it, check the example config file or direct message me on Discord (`@nickac`) for more help.

As usual, if you have any issues or feature requests, feel free to open up an issue here in the repository.
